version: "3"
services:
   bot:
      build: src/
      entrypoint:
      - python
      - PNBot.py
      volumes:
        - "./configs/config.prod.json:/app/config.json"
        - "./configs/guildSettings.prod.json:/app/guildSettings.json"
        - "./data:/app/data"
      restart: always
